PROJECT_ID: spring-datastore-381909

spring:
  main:
    allow-circular-references: true

  cloud:
    gcp:
      credentials:
        location: classpath:key.json
      datastore:
        namespace: ${DATASTORE_NAME:spring-cloud}
        project-id: ${PROJECT_ID:spring-datastore-381909}
        enabled: true
